/* Chromium automation at project-site paths. Synthetic data only.
   Physical iOS installation, safe-area cutouts and OS termination require manual QA. */
const {chromium,root,output,executablePath}=require('./support.cjs');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const fixture=JSON.parse(fs.readFileSync(path.join(root,'demo/fictional-program.json'),'utf8'));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pmd-shell-test-'));
for(const file of ['index.html','sw.js','manifest.webmanifest','assets','icons'])fs.cpSync(path.join(root,file),path.join(temp,file),{recursive:true});
process.env.PMD_SERVE_ROOT=temp;const server=require('../tools/serve.cjs');
const results=[],errors=[],consoleErrors=[],external=[];let browser,page,context,url;
const clone=x=>JSON.parse(JSON.stringify(x));
async function check(name,fn){const start=Date.now();try{const detail=await fn();results.push({name,status:'PASS',ms:Date.now()-start,detail:detail??null});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',ms:Date.now()-start,error:e.message});console.log('FAIL',name,e.message);}}
async function run(name,fn,arg){return check(name,()=>page.evaluate(fn,arg));}
async function watch(p){p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(url.split('/PMD-Toolkit/')[0]))external.push(r.url());});p.on('dialog',d=>d.accept());}
async function boot(p=page){await p.goto(url);await p.locator('.pc-boot').waitFor({state:'detached'});}
async function reset(){await page.evaluate(()=>{pmdDevice.enabled=false;clearTimeout(pmdDevice.timer);pmdCloseSheet();closeConfirm();document.querySelectorAll('.modal-overlay.open').forEach(e=>closeModal(e.id));appState=pmdBlankState();Object.values(SNAPSHOT_GLOBAL_COUNTERS).forEach(c=>c.set(1));_auditLog=[];undoStack=[];redoStack=[];PMD_COMPANION.desktopOnPhone=false;pmdApplyConfig();updateHeader();switchModule('dashboard');});}
async function populated(){await reset();await page.evaluate(b=>pmdCommitImport(pmdBuildImport(b)),fixture);await page.evaluate(()=>{document.getElementById('toastContainer').innerHTML='';});}
async function newContext(opts={}){const c=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,...opts});const p=await c.newPage();await watch(p);return {c,p};}
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));url='http://127.0.0.1:'+server.address().port+'/PMD-Toolkit/';
 browser=await chromium.launch({executablePath,headless:true});({c:context,p:page}=await newContext());await boot();
 await run('Fresh hosted launch: blank, Session Mode, no device database',async()=>{if(Object.keys(PMD_COUNTERS).some(k=>appState[k].length)||pmdDevice.enabled)throw Error('Not blank Session Mode');const dbs=await indexedDB.databases();if(dbs.some(d=>d.name.startsWith('pmd-trusted-device:')))throw Error('Session created device storage');if(localStorage.length||sessionStorage.length)throw Error('Web Storage used');return {domNodes:document.querySelectorAll('*').length,version:PMD_VERSION};});
 await check('Blank modules at all seven requested sizes',async()=>{const metrics=[];for(const [width,height]of [[320,700],[360,800],[390,844],[430,932],[844,390],[768,1024],[1440,1000]]){await page.setViewportSize({width,height});const row=await page.evaluate(()=>{const issues=[];PMD_MODULES.forEach(m=>appState.settings.modules[m.key].enabled=true);pmdApplyConfig();for(const m of PMD_MODULES){switchModule(m.key);if(/Render Error|NaN|Infinity/.test(document.getElementById('contentArea').innerText))issues.push(m.key);if(document.documentElement.scrollWidth>innerWidth+1)issues.push(m.key+' overflow');}if(issues.length)throw Error(issues.join(', '));return {width:innerWidth,height:innerHeight,companion:pmdPhone(),modules:PMD_MODULES.length};});if(width===844)assert.equal(row.companion,true);metrics.push(row);}return metrics;});
 await check('Mobile navigation, renamed modules, reorder and disabled preservation',async()=>{await populated();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{appState.settings.moduleNames.actions='Delivery queue';appState.settings.modules.actions.order=-1;appState.settings.modules.evm.enabled=false;pmdApplyConfig();renderContent();});await page.getByRole('button',{name:'Modules',exact:true}).click();assert.equal(await page.locator('#pcSheet [data-route]').first().getAttribute('data-route'),'actions');assert.equal(await page.locator('#pcSheet [data-route=evm]').count(),0);await page.locator('#pcSheet [data-route=actions]').click();assert.equal(await page.locator('#contentArea h1').textContent(),'Delivery queue');assert.equal(await page.evaluate(()=>appState.evmPackages.length),1);});
 await check('Quick Add and edit use custom statuses and preserve deep fields',async()=>{await page.evaluate(()=>{appState.settings.dropdownLists.actionStatuses=['Queued','Active','Finished'];appState.settings.statusRules.actions.closed=['Finished'];pmdApplyConfig();});await page.getByRole('button',{name:'New',exact:true}).click();await page.locator('[data-quick=actions]').click();await page.locator('#pcQuickTitle').fill('SYNTHETIC capture from meeting');await page.locator('#pcQuickOwner').fill('Fictional coordinator');await page.locator('#pcQuickDate').fill('2030-10-08');await page.locator('#pcQuickStatus').selectOption('Active');await page.locator('#pcQuickNotes').fill('Capture context');await page.getByRole('button',{name:'Save item',exact:true}).click();const id=await page.evaluate(()=>appState.actions.at(-1).id);await page.evaluate(id=>{appState.actions.find(r=>r.id===id).linkedRiskId='R-001';},id);await page.getByRole('button',{name:'Quick edit',exact:true}).click();await page.locator('#pcQuickStatus').selectOption('Finished');await page.locator('#pcQuickOwner').fill('Fictional reviewer');await page.getByRole('button',{name:'Save changes',exact:true}).click();const r=await page.evaluate(id=>appState.actions.find(r=>r.id===id),id);assert.equal(r.linkedRiskId,'R-001');assert.equal(r.assignee,'Fictional reviewer');assert.equal(r.status,'Finished');assert.ok(r.completed);assert.ok(await page.evaluate(()=>_auditLog.some(e=>JSON.stringify(e).includes('Active'))));});
 await check('Append dated note, keyboard trap and focus return',async()=>{await page.getByRole('button',{name:'Add note',exact:true}).click();await page.locator('#pcAppendNote').fill('SYNTHETIC meeting note');await page.locator('[data-save-note]').click();assert.ok(await page.evaluate(()=>appState.actions.at(-1).notes.some(n=>n.text==='SYNTHETIC meeting note')));await page.locator('#pcSheet footer button').last().focus();await page.keyboard.press('Tab');assert.ok(await page.locator('#pcSheet [data-close-sheet]').first().evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');assert.ok(await page.locator('#pcSheet').evaluate(e=>e.hidden));});
 await check('Search finds part/vendor/nested notes and opens linked record',async()=>{await page.evaluate(()=>{appState.purchases[0].vendor='SYNTHETIC unique vendor';markUnsaved();});await page.getByRole('button',{name:'Search',exact:true}).click();await page.locator('#pcSearch').fill('unique vendor');await page.locator('#pcSearchResults .pc-record').waitFor();await page.locator('#pcSearchResults .pc-record').click();assert.ok((await page.locator('#pcSheet').innerText()).includes('Order prototype interface materials'));await page.keyboard.press('Escape');await page.getByRole('button',{name:'Search',exact:true}).click();await page.locator('#pcSearch').fill('SYNTHETIC meeting note');await page.locator('#pcSearchResults .pc-record').waitFor();assert.equal(await page.locator('#pcSearchResults .pc-record').count(),1);await page.keyboard.press('Escape');});
 for(const key of ['risks','decisions','milestones','anomalies','procurement','lessons'])await check('Minimal quick capture: '+key,async()=>{await page.evaluate(k=>pmdOpenQuick(k),key);await page.locator('#pcQuickTitle').fill('SYNTHETIC quick '+key);await page.getByRole('button',{name:'Save item',exact:true}).click();assert.equal(await page.locator('#pcQuickForm').count(),0);assert.ok(await page.evaluate(k=>pmdRecords(k).some(r=>pmdTitle(r)==='SYNTHETIC quick '+k),key));await page.keyboard.press('Escape');});
 await run('Quick capture validates required title without mutation',()=>{const before=appState.actions.length;pmdOpenQuick('actions');document.getElementById('pcQuickTitle').value='';pmdSaveQuick(document.getElementById('pcQuickForm'));if(appState.actions.length!==before||!document.getElementById('pcQuickError').textContent)throw Error('Invalid capture saved');pmdCloseSheet();});
 await check('Mobile owner/open/overdue/status filters and sorting',async()=>{await page.evaluate(()=>{switchModule('actions');appState.actions[0].assignee='Fictional owner';appState.actions[0].status='Active';appState.actions[0].due='2001-01-01';markUnsaved();renderContent();});await page.getByRole('button',{name:'Filters',exact:true}).click();await page.locator('#pcFilterOpen').check();await page.locator('#pcFilterOverdue').check();await page.locator('#pcFilterOwner').selectOption('Fictional owner');await page.locator('#pcFilterSort').selectOption('date');await page.locator('[data-apply-filters]').click();assert.equal(await page.locator('#pcRecords .pc-record').count(),1);await page.locator('#pcListSearch').fill('NO_MATCH');await page.waitForTimeout(250);assert.equal(await page.locator('#pcRecords .pc-record').count(),0);await page.evaluate(()=>{PMD_COMPANION.filters={};PMD_COMPANION.query='';renderContent();});});
 await check('Every populated module at every requested size',async()=>{await populated();const widths=[[320,700],[360,800],[390,844],[430,932],[844,390],[768,1024],[1440,1000]];for(const [width,height]of widths){await page.setViewportSize({width,height});await page.evaluate(()=>{for(const m of PMD_MODULES){appState.settings.modules[m.key].enabled=true;switchModule(m.key);if(/Render Error|NaN|Infinity/.test(document.getElementById('contentArea').innerText))throw Error(m.key+' render');if(document.documentElement.scrollWidth>innerWidth+1)throw Error(m.key+' page overflow at '+innerWidth);}});}return {viewports:widths.length,moduleRenders:widths.length*21};});
 await check('All mobile record details and individual edit paths',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{for(const m of PMD_MODULES){for(const e of pmdMobileCollections(m.key)){pmdOpenMobileRecord(e.array,e.record.id);if(document.getElementById('pcSheet').hidden)throw Error(e.array+' detail hidden');pmdCloseSheet();}}});for(const key of ['requirements','tests','inventory','boms','evm','changes','costTracker','tradeStudies']){await page.evaluate(k=>pmdOpenQuick(k,1),key);await page.locator('#pcQuickTitle').fill('SYNTHETIC reviewed '+key);await page.getByRole('button',{name:'Save changes',exact:true}).click();assert.ok(await page.evaluate(k=>pmdTitle(pmdRecords(k)[0]).includes('reviewed'),key));await page.keyboard.press('Escape');}return true;});
 await run('Repeated render and modal cycles do not duplicate handlers',()=>{const n=appState.actions.length;for(let i=0;i<15;i++){switchModule('actions');pmdOpenQuick('actions');pmdCloseSheet();}pmdOpenQuick('actions');document.getElementById('pcQuickTitle').value='SYNTHETIC once';document.getElementById('pcQuickForm').requestSubmit();if(appState.actions.length!==n+1)throw Error('Duplicate event handling');pmdCloseSheet();});
 await run('Undo/redo and intentional relationship deletion on companion',()=>{const before=pmdRelated('risks',1).length;pmdDelete('risks',1);document.getElementById('confirmBtn').click();if(pmdFind({module:'risks',id:1}))throw Error('Delete failed');performUndo();if(!pmdFind({module:'risks',id:1})||pmdRelated('risks',1).length!==before)throw Error('Undo links failed');performRedo();if(pmdFind({module:'risks',id:1}))throw Error('Redo failed');performUndo();});
 await check('Mobile backup download and validated round trip',async()=>{const promise=page.waitForEvent('download');await page.evaluate(()=>exportAllData());const download=await promise;await download.saveAs(path.join(output,'mobile-backup.json'));const backup=JSON.parse(fs.readFileSync(path.join(output,'mobile-backup.json'),'utf8'));assert.equal(backup.schemaVersion,1);await page.evaluate(b=>{const p=pmdBuildImport(b);if(JSON.stringify(p.state.relationships)!==JSON.stringify(b.state.relationships))throw Error('Links lost');},backup);return {bytes:fs.statSync(path.join(output,'mobile-backup.json')).size};});
 await check('Share Backup download fallback',async()=>{await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false});});const promise=page.waitForEvent('download');await page.evaluate(()=>pmdShareBackup());const d=await promise;assert.ok(d.suggestedFilename().endsWith('.json'));});
 await check('Malformed file import leaves live program intact',async()=>{const before=await page.evaluate(()=>JSON.stringify(appState));await page.locator('#importFileInput').setInputFiles({name:'malformed.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.getByRole('heading',{name:'Import rejected'}).waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(appState)),before);await page.keyboard.press('Escape');});
 await run('Generated handler registry covers rendered workstation templates',()=>{if(pmdSecurityRejectedCount)throw Error(pmdSecurityRejectedCount+' legitimate handlers were rejected');return true;});
 await run('XSS payloads are inert in render sinks and imported fields',()=>{window.__pmdAttack=0;const payload='<img src=x onerror="window.__pmdAttack=1"><svg onload="window.__pmdAttack=2"></svg><script>window.__pmdAttack=3<\/script>';const b=pmdBackup();b.state.actions[0].title=payload;b.state.actions[0].description='\" autofocus onfocus=\"window.__pmdAttack=4';pmdCommitImport(pmdBuildImport(b));switchModule('actions');pmdOpenMobileRecord('actions',1);const div=document.createElement('div');div.innerHTML=payload+'<a href="java\nscript:window.__pmdAttack=5">x</a><script src="assets/app.js"><\/script>';if(div.querySelector('script,[onerror],[onload],[onfocus]')||div.querySelector('a').hasAttribute('href'))throw Error('Unsafe DOM survived');if(window.__pmdAttack)throw Error('Payload executed');div.remove();pmdCloseSheet();for(const url of ['javascript:alert(1)','java\tscript:alert(1)','data:text/html,x','vbscript:msgbox(1)','file:///test'])if(sanitizeLinkUrl(url)!=='#')throw Error('Unsafe URL accepted '+url);return true;});
 await check('Session Mode reload intentionally clears program',async()=>{await page.reload();await page.locator('.pc-boot').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>appState.actions.length),0);assert.equal(await page.evaluate(()=>pmdDevice.enabled),false);assert.equal((await page.evaluate(()=>indexedDB.databases())).filter(d=>d.name.startsWith('pmd-trusted-device:')).length,0);});
 await check('Trusted Device Mode requires explicit opt-in and commits save',async()=>{await populated();await page.evaluate(()=>pmdOpenDevice());await page.locator('[data-enable-device]').click();await page.locator('[data-confirm-device]').click();assert.equal(await page.evaluate(()=>pmdDevice.enabled),false);await page.locator('#pcTrustConsent').check();await page.locator('[data-confirm-device]').click();await page.waitForFunction(()=>pmdDevice.state==='Saved on this device');assert.equal(await page.evaluate(()=>pmdDevice.enabled),true);const saved=await page.evaluate(()=>pmdReadDevice(pmdDevice.db));assert.equal(saved.format,1);assert.equal(saved.current.schemaVersion,1);await page.keyboard.press('Escape');});
 await check('Trusted Device Mode restores after reload with audit and relationships',async()=>{const before=await page.evaluate(()=>({actions:appState.actions,relationships:appState.relationships,audit:_auditLog}));await page.reload();await page.locator('.pc-boot').waitFor({state:'detached'});assert.deepEqual(await page.evaluate(()=>({actions:appState.actions,relationships:appState.relationships,audit:_auditLog})),before);assert.ok(await page.evaluate(()=>pmdDevice.enabled));});
 await check('Quota failure keeps memory and prior device save',async()=>{const outcome=await page.evaluate(async()=>{const before=await pmdReadDevice(pmdDevice.db),original=pmdDevice.db.transaction;pmdDevice.db.transaction=()=>{throw new DOMException('Synthetic quota failure','QuotaExceededError');};appState.actions[0].title='SYNTHETIC unsaved quota change';markUnsaved();const ok=await pmdSaveDevice();pmdDevice.db.transaction=original;const after=await pmdReadDevice(pmdDevice.db);return {ok,before:before.current.state.actions[0].title,after:after.current.state.actions[0].title,memory:appState.actions[0].title,state:pmdDevice.state};});assert.equal(outcome.ok,false);assert.equal(outcome.before,outcome.after);assert.equal(outcome.memory,'SYNTHETIC unsaved quota change');assert.match(outcome.state,/failed/);await page.evaluate(()=>pmdSaveDevice());return outcome;});
 await check('Concurrent windows cannot silently overwrite device program',async()=>{const second=await context.newPage();await watch(second);await boot(second);await page.evaluate(async()=>{appState.actions[0].title='SYNTHETIC first window';markUnsaved();await pmdSaveDevice();});const ok=await second.evaluate(async()=>{appState.actions[0].title='SYNTHETIC conflicting window';markUnsaved();return await pmdSaveDevice();});assert.equal(ok,false);assert.equal(await page.evaluate(async()=>(await pmdReadDevice(pmdDevice.db)).current.state.actions[0].title),'SYNTHETIC first window');await second.evaluate(()=>{pmdDevice.enabled=false;clearTimeout(pmdDevice.timer);});await second.close();});
 await check('Corrupted current save offers previous validated recovery',async()=>{await page.evaluate(async()=>{await pmdSaveDevice();pmdDevice.enabled=false;clearTimeout(pmdDevice.timer);const saved=await pmdReadDevice(pmdDevice.db);saved.current={schema:'broken'};await new Promise((resolve,reject)=>{const tx=pmdDevice.db.transaction('program','readwrite');tx.objectStore('program').put(saved,'active');tx.oncomplete=resolve;tx.onerror=reject;});});await page.reload();await page.locator('.pc-boot').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>appState.actions.length),0);await page.locator('[data-restore-device=previous]').click();await page.waitForFunction(()=>pmdDevice.enabled);assert.ok(await page.evaluate(()=>appState.actions.length>0));await page.evaluate(()=>pmdSaveDevice());});
 await check('Disable and clear removes both saved copies, retains session',async()=>{const count=await page.evaluate(()=>appState.actions.length);await page.evaluate(()=>pmdDisableDevice());await page.locator('[data-confirm-clear-device]').click();await page.waitForFunction(()=>pmdDevice.enabled===false&&pmdDevice.revision===0);assert.equal(await page.evaluate(()=>appState.actions.length),count);assert.equal(await page.evaluate(()=>pmdReadDevice(pmdDevice.db)),undefined);await page.reload();await page.locator('.pc-boot').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>appState.actions.length),0);});
 await check('Malformed device envelope recovers without partial import',async()=>{await page.evaluate(async()=>{const db=pmdDevice.db||(pmdDevice.db=await pmdOpenDB(true));await new Promise(resolve=>{const tx=db.transaction('program','readwrite');tx.objectStore('program').put({format:99,revision:1,current:{bad:true}},'active');tx.oncomplete=resolve;});});await page.reload();await page.locator('.pc-boot').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>appState.actions.length),0);assert.ok(await page.locator('[data-disable-device]').isVisible());await page.locator('[data-disable-device]').click();await page.locator('[data-confirm-clear-device]').click();await page.waitForFunction(()=>pmdDevice.recovery===null);await page.keyboard.press('Escape');});
 await check('Service worker registers at GitHub project scope and caches shell only',async()=>{await page.waitForFunction(()=>pmdShell.ready&&navigator.serviceWorker.controller);const result=await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration(),keys=await caches.keys(),cache=await caches.open(keys.find(k=>k.endsWith(':'+r.scope))),urls=(await cache.keys()).map(r=>r.url);return {scope:r.scope,urls};});assert.equal(result.scope,url);assert.ok(result.urls.every(u=>u.startsWith(url)));assert.ok(!result.urls.some(u=>/backup|demo|test|export/i.test(u)));return {scopePath:new URL(result.scope).pathname,shellEntries:result.urls.length};});
 await check('Offline shell reload succeeds and remains blank in Session Mode',async()=>{await context.setOffline(true);await page.reload();await page.locator('.pc-boot').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>appState.actions.length),0);assert.ok((await page.locator('#pcSaveState').innerText()).includes('Offline'));await page.locator('[data-sheet=new]').click();await page.locator('[data-quick=actions]').click();await page.locator('#pcQuickTitle').fill('SYNTHETIC offline capture');await page.getByRole('button',{name:'Save item',exact:true}).click();assert.equal(await page.evaluate(()=>appState.actions.length),1);await page.keyboard.press('Escape');await context.setOffline(false);});
 await check('Update waits for intent, backup acknowledgment, and other windows',async()=>{const sw=path.join(temp,'sw.js');fs.writeFileSync(sw,fs.readFileSync(sw,'utf8').replace('pmd-10.1.0-1','pmd-10.1.0-test2'));await page.evaluate(()=>pmdShell.registration.update());await page.waitForFunction(()=>!!pmdShell.registration.waiting);assert.equal(await page.evaluate(()=>appState.actions.length),1);await page.evaluate(()=>pmdReviewUpdate());await page.locator('#pcApplyUpdate').click();assert.match(await page.locator('#pcUpdateError').innerText(),/Confirm/);const second=await context.newPage();await watch(second);await boot(second);await page.locator('#pcUpdateConsent').check();await page.locator('#pcApplyUpdate').click();await page.waitForFunction(()=>document.getElementById('pcUpdateError')?.textContent.includes('Another PMD window'));await second.close();await page.locator('#pcApplyUpdate').click();await page.waitForFunction(()=>!document.getElementById('pcUpdateConsent'));await page.locator('.pc-boot').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>appState.actions.length),0);const keys=await page.evaluate(()=>caches.keys());assert.ok(keys.some(k=>k.includes('test2')));assert.ok(!keys.some(k=>k.includes('10.1.0-1:')));});
 await check('Root-path deployment also works with relative manifest and worker paths',async()=>{const fresh=await newContext();await fresh.p.goto(url.replace('/PMD-Toolkit/','/'));await fresh.p.locator('.pc-boot').waitFor({state:'detached'});await fresh.p.waitForFunction(()=>pmdShell.ready);assert.equal(await fresh.p.evaluate(()=>new URL('./',location.href).pathname),'/');await fresh.c.close();});
 await check('5,000-record synthetic program: bounded rendering, cached search, import timing',async()=>{await reset();await page.setViewportSize({width:390,height:844});const metric=await page.evaluate(()=>{const arrays=['actions','requirements','tests','boms','purchases'];for(const key of arrays){const m=pmdModule(key);appState.settings.modules[m.key].enabled=true;for(let i=1;i<=1000;i++){const r={id:i,title:'SYNTHETIC '+key+' '+i,description:'Fictional performance record '+i,owner:'Example team',status:''};if(key==='boms')r.partName=r.title;if(key==='purchases')r.itemName=r.title;if(key==='actions')r.notes=[];appState[key].push(r);}const counter=PMD_COUNTERS[key];if(SNAPSHOT_GLOBAL_COUNTERS[counter])SNAPSHOT_GLOBAL_COUNTERS[counter].set(1001);else appState[counter]=1001;}pmdApplyConfig();let t=performance.now();switchModule('actions');const renderMs=performance.now()-t,rows=document.querySelectorAll('#pcRecords .pc-record').length,domNodes=document.querySelectorAll('*').length;t=performance.now();const first=pmdFindSearch('SYNTHETIC actions 990');const firstSearchMs=performance.now()-t;t=performance.now();pmdFindSearch('SYNTHETIC tests 500');const cachedSearchMs=performance.now()-t;t=performance.now();pmdBuildImport(pmdBackup());const importValidationMs=performance.now()-t;return {records:5000,rows,domNodes,renderMs,firstSearchMs,cachedSearchMs,importValidationMs,heapBytes:performance.memory?.usedJSHeapSize,matches:first.length};});assert.equal(metric.rows,40);assert.ok(metric.domNodes<2500);assert.ok(metric.renderMs<1000);assert.ok(metric.cachedSearchMs<250);assert.ok(metric.importValidationMs<3000);await page.locator('[data-page="1"]').click();assert.equal(await page.evaluate(()=>PMD_COMPANION.page),1);return metric;});
 await check('Desktop large register remains paginated and efficient',async()=>{await page.setViewportSize({width:1440,height:1000});const metric=await page.evaluate(()=>{const t=performance.now();switchModule('actions');return {ms:performance.now()-t,rows:document.querySelectorAll('#contentArea tbody tr').length,nodes:document.querySelectorAll('#contentArea *').length};});assert.ok(metric.ms<2000);assert.ok(metric.rows<=100);return metric;});
 await check('Simulated 4× CPU slowdown: startup and mobile rendering',async()=>{const session=await context.newCDPSession(page);await session.send('Emulation.setCPUThrottlingRate',{rate:4});await page.setViewportSize({width:390,height:844});const elapsed=await page.evaluate(()=>{let t=performance.now();switchModule('actions');return performance.now()-t;});assert.ok(elapsed<2000);await session.send('Emulation.setCPUThrottlingRate',{rate:1});return {mobile5000ProgramRenderMs:elapsed,throttle:4};});
 await check('Light/dark screenshots, touch targets, and mobile form layout',async()=>{await populated();await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{switchModule('dashboard');});await page.screenshot({path:path.join(output,'iphone-dashboard-dark.png')});await page.evaluate(()=>{switchModule('actions');});await page.screenshot({path:path.join(output,'iphone-actions.png')});await page.evaluate(()=>pmdOpenMobileRecord('actions',1));await page.screenshot({path:path.join(output,'iphone-detail.png')});await page.locator('[data-quick=actions]').click();await page.screenshot({path:path.join(output,'iphone-quick-edit.png')});assert.ok(await page.locator('#pcQuickTitle').evaluate(e=>getComputedStyle(e).fontSize==='16px'));const targets=await page.locator('#pcSheet footer button,#pcNav button').evaluateAll(es=>es.map(e=>({height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width})));assert.ok(targets.every(t=>t.height>=44&&t.width>=44));await page.keyboard.press('Escape');await page.evaluate(()=>{toggleTheme();switchModule('dashboard');});await page.screenshot({path:path.join(output,'iphone-dashboard-light.png')});await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{toggleTheme();switchModule('dashboard');});await page.screenshot({path:path.join(output,'desktop-dashboard.png')});await page.evaluate(()=>switchModule('actions'));await page.screenshot({path:path.join(output,'desktop-actions.png')});await reset();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'iphone-blank.png')});return targets;});
 await check('Print report produces a readable document',async()=>{await populated();await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>pmdProgramReport());await page.emulateMedia({media:'print'});await page.pdf({path:path.join(output,'program-report.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});assert.ok(fs.statSync(path.join(output,'program-report.pdf')).size>10000);});
 await check('No unhandled browser exceptions or external data requests',()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);return {errors:0,externalRequests:0,consoleErrors};});
})().catch(e=>{console.error(e);results.push({name:'Suite execution',status:'FAIL',error:e.message});}).finally(async()=>{fs.writeFileSync(path.join(output,'companion-results.json'),JSON.stringify({executedAt:new Date().toISOString(),browser:'Chromium desktop engine; mobile/touch emulation',results,errors,consoleErrors,external},null,2));await browser?.close();await new Promise(resolve=>server.close(resolve));fs.rmSync(temp,{recursive:true,force:true});if(results.some(r=>r.status==='FAIL'))process.exitCode=1;});
