/* Synthetic adversarial and workflow regression checks for PMD 10.2. */
const {chromium,root,output,executablePath}=require('./support.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const server=require('../tools/serve.cjs'),results=[],errors=[],external=[];let browser,context,page,url;
async function check(name,fn){try{const detail=await fn();results.push({name,status:'PASS',detail:detail??null});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message);}}
async function run(name,fn){return check(name,()=>page.evaluate(fn));}
async function boot(p){await p.goto(url);await p.locator('.pc-boot').waitFor({state:'detached'});}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/PMD-Toolkit/';
 browser=await chromium.launch({executablePath});context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(new URL(url).origin))external.push(r.url());});await boot(page);
 await run('Fresh 10.2 launch preserves blank Session Mode without program storage',async()=>{if(PMD_VERSION!=='10.2.0'||Object.keys(PMD_COUNTERS).some(k=>appState[k].length))throw Error('Unexpected production data/version');if((await indexedDB.databases()).length||pmdDevice.enabled||pmdDevice.channel)throw Error('Unexpected program persistence');});
 await run('Malformed nested metadata is rejected before mutation',()=>{
   const before=JSON.stringify(appState),cases=[
    b=>b.state.actions=[{id:1,title:'SYNTHETIC',notes:[{date:{bad:1},text:[]}]}],
    b=>b.session.savedFilters={actions:{bad:1}},b=>b.session.savedFilters={actions:[{name:'SYNTHETIC',filters:null}]},
    b=>b.auditTrail=[{timestamp:{bad:1},module:[],action:{},changes:[]}],b=>b.session.raci={x:'INVALID'},b=>b.session.subViews={actions:[]},
    b=>b.state.actions=[{id:Number.MAX_SAFE_INTEGER,title:'SYNTHETIC'}],b=>b.state.actions=[{id:1,title:'SYNTHETIC',due:'2026-02-30'}],
    b=>b.state.settings.prefixHistory={actions:'AI'},b=>b.state.settings.dashboard.attention='yes',
    b=>b.state.linkSections=[{id:1,links:[{id:-1,url:'https://example.invalid'}]}]
   ];for(const mutate of cases){const b=pmdBackup();mutate(b);let rejected=false;try{pmdBuildImport(b);}catch{rejected=true;}if(!rejected)throw Error('Invalid metadata accepted');}if(before!==JSON.stringify(appState))throw Error('Working state changed');return {cases:cases.length};
 });
 await run('Risk dimension collisions and non-JSON objects cannot enter a backup',()=>{for(const key of ['history','notes','priority','parentId','created','qty']){const b=pmdBackup();b.state.settings.riskModel=pmdRiskPreset('product');b.state.settings.riskModel.dimensions[0].key=key;let no=false;try{pmdBuildImport(b);}catch{no=true;}if(!no)throw Error('Collision accepted '+key);}for(const value of [new Date(),undefined,()=>{},NaN]){let no=false;try{pmdValidateJSON({value});}catch{no=true;}if(!no)throw Error('Non-JSON accepted');}const cycle={};cycle.self=cycle;try{pmdValidateJSON(cycle);throw Error('Cycle accepted');}catch(e){if(e.message==='Cycle accepted')throw e;}});
 await run('Prototype-shaped text remains valid data and renders in grouped views',()=>{appState.settings.modules.procurement.enabled=true;appState.purchases=['__proto__','constructor','toString'].map((vendor,i)=>({id:i+1,itemName:'SYNTHETIC purchase',vendor}));appState.costItems=['__proto__','constructor'].map((wbsCode,i)=>({id:i+1,title:'SYNTHETIC cost',wbsCode}));appState._purchaseNextId=4;appState._costNextId=3;pmdBuildImport(pmdBackup());renderProcurementModule(document.createElement('div'));renderCostTrackerModule(document.createElement('div'));});
 await run('Nested active markup, SVG mutation and link tracking attributes removed',()=>{const el=document.createElement('div');el.innerHTML='<template><img src="https://example.invalid/pixel" onerror="alert(1)"></template><svg><a href="#"><set attributeName="href" to="javascript:alert(1)"></set></a></svg><a href="https://example.invalid" ping="https://example.invalid/ping" attributionsrc="https://example.invalid/track">Test</a>';if(el.querySelector('template,set,[ping],[attributionsrc]'))throw Error('Unsafe nested content survived');const a=el.querySelector('a[href^="https"]');if(a.referrerPolicy!=='no-referrer'||!a.rel.includes('noreferrer'))throw Error('External referrer boundary missing');});
 await run('All spreadsheet cell paths protect formulas and preserve numeric zero',()=>{for(const text of ['=1+1','+cmd','@SUM(1)','-1+2',' \t=1+1','\r=1+1','\n+cmd','＝1+1'])if(!pmdCSVCell(text).startsWith('"\''))throw Error('Formula-like text not neutralized');if(pmdCSVCell(0)!=='"0"'||pmdCSVCell(-2)!=='"-2"')throw Error('Measured numbers lost');});
 await check('Actual CSV download uses shared neutralization',async()=>{await page.evaluate(()=>{appState.actions=[{id:1,title:'\t=1+1',notes:[]}];_actionNextId=2;});const promise=page.waitForEvent('download');await page.evaluate(()=>exportModuleCsv('actions'));const download=await promise;const file=path.join(output,'resilience.csv');await download.saveAs(file);assert.ok(fs.readFileSync(file,'utf8').includes('"\'\t=1+1"'));});
 await check('Quick capture Escape keeps typed text until explicit discard',async()=>{await page.evaluate(()=>pmdOpenQuick('actions'));await page.locator('#pcQuickTitle').fill('SYNTHETIC unfinished capture');await page.keyboard.press('Escape');assert.equal(await page.locator('#pcQuickTitle').inputValue(),'SYNTHETIC unfinished capture');await page.locator('#pcKeepEditing').click();assert.equal(await page.locator('#pcDiscard').count(),0);await page.locator('#pcSheet [data-close-sheet]').first().click();await page.locator('#pcDiscardForm').click();assert.ok(await page.locator('#pcSheet').evaluate(e=>e.hidden));assert.equal(await page.evaluate(()=>appState.actions.length),1);});
 await check('Notes receive the same discard protection and save once',async()=>{await page.evaluate(()=>pmdOpenMobileRecord('actions',1));await page.locator('[data-add-note]').click();await page.locator('#pcAppendNote').fill('SYNTHETIC retained meeting note');await page.keyboard.press('Escape');await page.locator('#pcKeepEditing').click();await page.locator('[data-save-note]').click();assert.equal(await page.evaluate(()=>appState.actions[0].notes.length),1);await page.keyboard.press('Escape');assert.ok(await page.locator('#pcSheet').evaluate(e=>e.hidden));});
 await run('Review dates exclude historical execution dates and include scheduled tests/reviews',()=>{appState.settings.modules.tests.enabled=true;appState.tests=[{id:1,title:'SYNTHETIC execution history',testDate:'2000-01-01',result:''},{id:2,title:'SYNTHETIC scheduled',scheduledDate:todayStr(),result:''}];appState.decisions=[{id:1,title:'SYNTHETIC review',reviewDate:todayStr(),status:''}];appState._testNextId=3;appState._decNextId=2;markUnsaved();const upcoming=pmdUpcoming();if(!upcoming.some(x=>x.module==='tests'&&x.id===2)||!upcoming.some(x=>x.module==='decisions'))throw Error('Scheduled work missing');if(pmdAttention().some(x=>x.module==='tests'&&x.id===1))throw Error('Historical test misclassified overdue');});
 await check('Review queue pages beyond 100 records, filters owner and retains return context',async()=>{await page.evaluate(()=>{appState.actions=Array.from({length:145},(_,i)=>({id:i+1,title:'SYNTHETIC action '+String(i+1).padStart(3,'0'),assignee:i%2?'Fictional reviewer':'Fictional coordinator',due:'2000-01-01',notes:[]}));_actionNextId=146;markUnsaved();pmdOpenQueue('attention');});assert.equal(await page.locator('#pcReviewResults .pc-record').count(),30);for(let i=0;i<4;i++)await page.locator('[data-review-page="1"]').click();assert.equal(await page.locator('#pcReviewResults .pc-record').count(),25);await page.locator('#pcReviewFilters summary').click();await page.locator('#pcReviewOwner').selectOption('Fictional reviewer');assert.match(await page.locator('#pcReviewResults').innerText(),/72 matching/);await page.locator('#pcReviewResults .pc-record').first().click();await page.locator('[data-back-review]').click();assert.equal(await page.locator('#pcReviewOwner').inputValue(),'Fictional reviewer');});
 await check('Review and backup sheets fit phone/tablet/desktop and both themes',async()=>{const widths=[320,360,390,430,768,1440];for(const width of widths){await page.setViewportSize({width,height:900});for(const theme of ['dark','light']){await page.evaluate(theme=>{appState.settings.theme=theme;pmdApplyConfig();pmdOpenReview();},theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.ok(await page.locator('#pcReviewResults .pc-record').first().isVisible());await page.evaluate(()=>pmdOpenBackupCenter());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);}}await page.setViewportSize({width:390,height:844});});
 await check('Download does not falsely clear unsaved state; stale confirmation is refused',async()=>{await page.evaluate(()=>{appState.settings.programName='SYNTHETIC private title';markUnsaved();pmdOpenBackupCenter();});const promise=page.waitForEvent('download');await page.locator('#pcSheet [data-backup]').click();const download=await promise;assert.ok(!download.suggestedFilename().includes('private'));assert.equal(await page.evaluate(()=>_hasUnsavedChanges),true);await page.evaluate(()=>{appState.actions[0].title='SYNTHETIC changed after export';markUnsaved();});await page.locator('#pcConfirmBackup').click();assert.equal(await page.evaluate(()=>_hasUnsavedChanges),true);});
 await check('Backup verification reads actual file without importing; confirmation covers current changes',async()=>{const promise=page.waitForEvent('download');await page.locator('#pcSheet [data-backup]').click();const download=await promise,file=path.join(output,'resilience-backup.json');await download.saveAs(file);const before=await page.evaluate(()=>JSON.stringify(appState));await page.locator('#pcVerifyBackup').setInputFiles(file);await page.waitForFunction(()=>document.getElementById('pcVerifyResult').textContent.includes('matches'));assert.equal(await page.evaluate(()=>JSON.stringify(appState)),before);await page.locator('#pcConfirmBackup').click();assert.equal(await page.evaluate(()=>_hasUnsavedChanges),false);await page.locator('#pcVerifyBackup').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForFunction(()=>document.getElementById('pcVerifyResult').textContent.includes('did not pass'));assert.equal(await page.evaluate(()=>JSON.stringify(appState)),before);});
 await run('Replacement preview counts changed, added and removed records without mutation',()=>{const before=JSON.stringify(appState),b=pmdBackup();b.state.actions=b.state.actions.slice(0,3);b.state.actions[0].title='SYNTHETIC replacement';b.state.actions.push({id:146,title:'SYNTHETIC addition'});const prepared=pmdBuildImport(b),html=pmdImportPreview(prepared,4);if(!html.includes('145 → 4')||!html.includes('<td>1</td><td>1</td><td>142</td>'))throw Error('Replacement counts incorrect');if(JSON.stringify(appState)!==before)throw Error('Preview mutated data');});
 await check('Saved filter creation from blank preset map is undoable and included in backups',async()=>{await page.evaluate(()=>{savedFilters={};});page.once('dialog',d=>d.accept('SYNTHETIC preset'));await page.evaluate(()=>saveCurrentFilter('actions'));assert.equal(await page.evaluate(()=>savedFilters.actions.length),1);await page.evaluate(()=>pmdBuildImport(pmdBackup()));await page.evaluate(()=>performUndo());assert.equal(await page.evaluate(()=>savedFilters.actions),undefined);await page.evaluate(()=>performRedo());assert.equal(await page.evaluate(()=>savedFilters.actions.length),1);});
 await check('Device revision notices pause stale windows without exchanging program data',async()=>{await page.evaluate(()=>pmdEnableDevice());await page.locator('#pcTrustConsent').check();await page.locator('[data-confirm-device]').click();await page.waitForFunction(()=>pmdDevice.state==='Saved on this device');const second=await context.newPage();await boot(second);await page.evaluate(async()=>{appState.actions[0].title='SYNTHETIC latest version';markUnsaved();await pmdSaveDevice();});await second.waitForFunction(()=>pmdDevice.paused);assert.equal(await second.evaluate(()=>pmdDevice.state),'Changed in another window — saving paused');assert.equal(await second.evaluate(()=>pmdSaveDevice()),false);await second.evaluate(()=>pmdOpenDevice());await second.locator('[data-review-saved-device]').click();await second.locator('[data-restore-device=current]').waitFor({state:'visible'});await second.locator('[data-restore-device=current]').click();assert.equal(await second.evaluate(()=>appState.actions[0].title),'SYNTHETIC latest version');await page.evaluate(()=>pmdClearDevice());await second.waitForFunction(()=>pmdDevice.paused);assert.equal(await second.evaluate(()=>pmdSaveDevice()),false);await second.close();});
 await run('Device envelope rejects unsafe revisions and invalid timestamps',()=>{for(const saved of [{format:1,revision:-1,savedAt:new Date().toISOString()},{format:1,revision:0,savedAt:new Date().toISOString()},{format:1,revision:1,savedAt:'invalid'},{format:2,revision:1,savedAt:new Date().toISOString()}])if(pmdDeviceEnvelope(saved))throw Error('Invalid device envelope accepted');});
 await run('Failed import commit restores records, counters, undo/redo and dirty state',()=>{pmdCloseSheet();markSaved();const before=JSON.stringify(appState),depth=undoStack.length,redoDepth=redoStack.length,prepared=pmdBuildImport(pmdBackup()),original=pmdApplyConfig;let first=true;pmdApplyConfig=function(){if(first){first=false;throw Error('Synthetic render failure');}return original();};prepared.state.settings.programName='SYNTHETIC rejected replacement';const ok=pmdCommitImport(prepared);pmdApplyConfig=original;if(ok||JSON.stringify(appState)!==before||undoStack.length!==depth||redoStack.length!==redoDepth||_hasUnsavedChanges)throw Error('Incomplete rollback');closeModal('pmdDialog');});
 await run('Numeric receipt audit values, including zero, remain portable and readable',()=>{auditRecord('actions',1,'updated',[{field:'Synthetic quantity',oldVal:0,newVal:2},{field:'Synthetic flag',oldVal:true,newVal:false}],'SYNTHETIC numeric history');const backup=pmdBackup();pmdBuildImport(backup);const html=renderAuditHistoryHTML('actions',1);if(!html.includes('>0</span>')||!html.includes('>false</span>'))throw Error('Numeric or boolean audit value lost');});
 await run('Relationship endpoints require real collection names',()=>{const b=pmdBackup();b.state.relationships=[{id:'synthetic',type:'relates to',from:{module:'toString',id:1},to:{module:'actions',id:1}}];let rejected=false;try{pmdBuildImport(b);}catch{rejected=true;}if(!rejected)throw Error('Prototype name accepted as collection');});
 await run('10,000 records and 10,000 combined links validate with bounded lookup cost',()=>{const b=pmdBackup();b.state.actions=[];b.state.risks=[];b.state.relationships=[];for(let i=1;i<=5000;i++){b.state.actions.push({id:i,title:'SYNTHETIC action '+i,linkedRiskId:'R-'+i,notes:[]});b.state.risks.push({id:i,title:'SYNTHETIC risk '+i,rackIds:[]});b.state.relationships.push({id:'synthetic-'+i,from:{module:'actions',id:i},to:{module:'risks',id:i},type:'relates to'});}const t=performance.now(),prepared=pmdBuildImport(b),ms=performance.now()-t;if(ms>3000||prepared.warnings.length)throw Error('Graph validation budget or reference regression');return {records:10000,explicitRelationships:5000,legacyReferences:5000,validateMs:ms};});
 await check('Current screenshots at desktop and phone widths',async()=>{await page.evaluate(()=>{appState.settings.programName='Fictional review workspace';appState.settings.setupComplete=true;appState.settings.theme='dark';pmdApplyConfig();updateHeader();renderContent();document.getElementById('toastContainer').innerHTML='';PMD_REVIEW.owner='';PMD_REVIEW.kind='attention';PMD_REVIEW.page=0;});await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>pmdOpenReview());await page.screenshot({path:path.join(output,'review-desktop.png')});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>pmdOpenReview());await page.screenshot({path:path.join(output,'review-iphone.png')});await page.evaluate(()=>pmdOpenBackupCenter());await page.screenshot({path:path.join(output,'backup-iphone.png')});});
 await run('Cancelled startup restore cannot replace an in-progress form with late recovery UI',async()=>{pmdOpenQuick('actions');document.getElementById('pcQuickTitle').value='SYNTHETIC working draft';const old=pmdReadDevice;pmdReadDevice=async()=>{pmdDevice.restoreCancelled=true;return {format:99};};await pmdInitDevice();pmdReadDevice=old;pmdDevice.restoreCancelled=false;if(document.getElementById('pcQuickTitle')?.value!=='SYNTHETIC working draft')throw Error('Late recovery replaced the form');pmdCloseSheet();});
 await check('No unhandled errors or off-origin runtime requests',()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);});
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();fs.writeFileSync(path.join(output,'resilience-results.json'),JSON.stringify({date:new Date().toISOString(),results},null,2));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;});
